allow-content-access = true
allow-flight = true
allow-noclip = true
allow-cheats = true
allow-destroy = true
allow-attack = true
allow-cheat-movement = true
allow-debug-cheats = true
allow-fast-interaction = true
