<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resource\Image\AppImg\IconApp.ico</ApplicationIcon>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resource\Image\SVG\icon.svg" />
    <None Remove="Resource\Image\SVG\logo.svg" />
    <None Remove="Resource\Image\SVG\trash.svg" />
    <None Remove="Resource\Language_dictionary\langs.json" />
    <None Remove="Resource\User\Default\controls.toml" />
    <None Remove="Resource\User\Default\settings.toml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resource\User\Default\settings_app.toml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resource\Image\AppImg\IconApp.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resource\User\Default\controls.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resource\User\Default\settings.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resource\User\Logs\" />
    <Folder Include="Resource\Data\Mods\" />
    <Folder Include="Resource\Data\Core\" />
    <Folder Include="Resource\Data\Forks\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.Common.NETCore" Version="132.3.11" />
    <PackageReference Include="CefSharp.Wpf.NETCore" Version="132.3.11" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.4.2" />
    <PackageReference Include="Tomlyn" Version="0.18.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resource\Image\SVG\icon.svg" />
    <Resource Include="Resource\Image\SVG\logo.svg" />
    <Resource Include="Resource\Image\SVG\trash.svg" />
    <Content Include="Resource\Language_dictionary\langs.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Resource\Language_dictionary\lang.en_US.xaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Page>
    <Page Update="Resource\Language_dictionary\lang.ru_RU.xaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
