player.noclip = "key:n"
movement.left = "key:a"
player.drop = "key:q"
devtools.console = "key:grave-accent"
player.flight = "key:f"
player.build = "mouse:right"
player.destroy = "mouse:left"
player.attack = "mouse:left"
player.fast_interaction = "key:x"
player.pick = "mouse:middle"
movement.right = "key:d"
movement.sprint = "key:left-ctrl"
movement.jump = "key:space"
movement.crouch = "key:left-shift"
movement.back = "key:s"
movement.forward = "key:w"
movement.cheat = "key:r"
chunks.reload = "key:f5"
camera.zoom = "key:c"
camera.mode = "key:f4"
hud.inventory = "key:tab"
